"""empty message

Revision ID: 46c8f5a834c9
Revises: 92fed3f8ae32
Create Date: 2020-03-22 19:21:15.870720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c8f5a834c9'
down_revision = '92fed3f8ae32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_liked', sa.Integer(), nullable=True),
    sa.Column('post_liked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_liked'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_liked'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
